feat: added support for merchant view android
juspay/hyper-sdk-react pull request #35
Opened 2024-02-08 08:33 UTC by Georgepadannamackal

Adding support for getMerchantView for react native plugin

2024-02-20 10:44 UTC, harshgarg18 requested changes

2024-02-20 10:44 UTC, harshgarg18 commented on android/src/main/java/in/juspay/hypersdkreact/HyperSdkReactModule.java
> +    private ReactInstanceManager rim;
Can we use proper names for this and rrv?

2024-02-20 10:44 UTC, harshgarg18 commented on android/src/main/java/in/juspay/hypersdkreact/HyperSdkReactModule.java
> +                                    rrv.startReactApplication(rim, "JuspayHeader");
As these constants are used in native code, we can expose them from here itself to js/ts to merchant

2024-02-20 10:44 UTC, harshgarg18 commented on src/index.tsx
> +  HyperSdkReact.updateMerchantViewHeight = () => {
can we use the same signature here as we have for iOS? 

```suggestion
  HyperSdkReact.updateMerchantViewHeight = (tag: string, height: number) => {
```

2024-02-20 10:44 UTC, harshgarg18 commented on ios/HyperSdkReact.mm
@balaganesh-juspay - could you please review this?

2024-05-09 05:58 UTC, harshgarg18 requested changes

2024-05-09 05:58 UTC, harshgarg18 commented on example/index.js
> +const HyperSdkReact = NativeModules.HyperSdkReact
this is the incorrect way of importing HyperSdkReact in example.

Can you import via 'hyper-sdk-react' package

2024-05-09 05:58 UTC, harshgarg18 commented on src/index.tsx
> +  HyperSdkReact.updateMerchantViewHeight = () => {
this change is still pending

2024-05-09 05:59 UTC, harshgarg18 commented
there are conflicts in the PR. Can you rebase and resolve them?

2024-05-09 07:46 UTC, abhijeetvermayash commented
POT 

https://github.com/juspay/hyper-sdk-react/assets/42650474/a13d88db-977c-4256-b0a4-b2bf469f2621

2024-05-09 10:59 UTC, harshgarg18 requested changes
Also, Can you get iOS code reviewed by @Subhash703 or @balaganesh-juspay ?

2024-05-09 10:59 UTC, harshgarg18 commented on android/src/main/java/in/juspay/hypersdkreact/HyperSdkReactModule.java
>          }};
We should also send FOOTER AND FOOTER_ATTACHED

2024-05-09 10:59 UTC, harshgarg18 commented on android/src/main/java/in/juspay/hypersdkreact/HyperSdkReactModule.java
> +                        if (reactInstanceManager == null) {
you need to add null check for activity too

2024-05-09 10:59 UTC, harshgarg18 commented on example/android/app/src/main/assets/index.android.bundle
don't commit this file

2024-05-09 10:59 UTC, harshgarg18 commented on example/android/app/src/main/res/drawable-mdpi/images_promotion.png
why do we have duplication of images between this and next one?

2024-05-09 10:59 UTC, harshgarg18 commented on example/android/app/src/main/res/drawable-mdpi/images_promotion.png
can you remove the one which is not needed?

2024-05-09 10:59 UTC, harshgarg18 commented on example/index.js
> +  () => TopViewAttached
TopViewAttached is not supposed to be for JuspayHeaderAttached?

2024-05-09 10:59 UTC, harshgarg18 commented on ios/HyperSdkReact.mm
> +         };
Same here, there should be JUSPAY_FOOTER and JUSPAY_FOOTER_ATTACHED too

2024-05-09 10:59 UTC, harshgarg18 commented on src/index.tsx
>  };
footer, footer attached

2024-05-09 11:17 UTC, balaganesh-juspay commented on ios/HyperSdkReact.mm
> +RCT_EXPORT_METHOD(updateMerchantViewHeight: (NSString * _Nonnull) tag height: (NSNumber * _Nonnull) h) {
@Georgepadannamackal When do they need to call this function? And will merchant be able to get the exact height of the view?

2024-05-09 12:42 UTC, balaganesh-juspay approved these changes

2024-05-09 12:54 UTC, harshgarg18 approved these changes

2024-05-09 14:05 UTC, merged